includePhonetic: true
includeOrigin: true
includeSynonyms: true
includeAntonyms: true
filterDefinitionsWithoutExamples: false
generateExplanations: true
generateExampleSentences: true
maxExampleSentences: 0